[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:uvicorn]
directory=/app/chatbot-saas-backend
command=uvicorn app.main:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
